### ISSUE TITLE
CryptoException: Mnemonic to KeyPair generation failed

### ISSUE THREAD

**Issue by rgouzal** [blockfrost/blockfrost-java#6]
When implementing the line below I get error:
`\Account account = new Account(Networks.testnet(), mnemonic);`

Error:
```
com.bloxbean.cardano.client.crypto.CryptoException: Mnemonic to KeyPair generation failed
        at com.bloxbean.cardano.client.crypto.cip1852.CIP1852.getKeyPairFromMnemonic(CIP1852.java:16)
        at com.bloxbean.cardano.client.account.Account.getHdKeyPair(Account.java:379)
        at com.bloxbean.cardano.client.account.Account.baseAddress(Account.java:191)
        at com.bloxbean.cardano.client.account.Account.<init>(Account.java:140)
        at com.bloxbean.cardano.client.account.Account.<init>(Account.java:124)
        at com.bloxbean.cardano.client.account.Account.<init>(Account.java:113)
```

**Comment by satran004** [comment]
@rgouzal, this is part of cardano-client-lib. Can you please create an issue at https://github.com/bloxbean/cardano-client-lib

Please also provide the following details
- No of words in mnemonic
- Language  (English or others)
- cardano-client-lib version and Operating system
- If possible, **TESTNET** mnemonic to reproduce the error.  (TESTNET)

**Comment by rgouzal** [comment]
Oh sorry, I thought its cardano-client-lib.
